<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/12/03 12:43:54

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sympro',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
